# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l8USWVjGNNUxGEtpqu5mGu3FRX6rALSM
"""

def Solution(X, A):
    a=[]
    b=[]
    count = -1
    array_len = len(A)
    for i in range(1,X+1):
      a.append(i)
    for j in range (0,array_len):
      b.append(A[j])
      count+=1
      mylist = list(dict.fromkeys(b))
      b.sort()
      if(all(x in b for x in a)): 
        print("Frog get to the other side at:",count,"sec")
        break
if __name__ == "__main__":
    X = 5
    A = [1, 3, 1, 4, 2, 3, 5, 4]

    Solution(X, A)